//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photoprint.WebSite.Views.Checkout.Controls.Shipping.PixlparkShippings.DDelivery {
    
    
    public partial class IFrame {
    }
}
